module.exports = {
  USER_SET_STEP: 'userSetStep',
  USER_LATENCY_CHECK: 'latencyCheck',
	USER_GAME_ACTION: 'gameAction',
	USER_ACTION_START: 'START',
	USER_ACTION_DONE: 'DONE',
	GAME_STAGE_STARTED: 'STARTED',
	GAME_STAGE_END: 'END',
	GAME_STAGE_RACE: 'RACE',
	GAME_STAGE_GAME_OVER: 'GAME OVER',
	GAME_STAGE_WAITING_ROOM: 'WAITING ROOM',
	GAME_STAGE_SET_PATH: 'SET PATH',
	GAME_ACTION_START: 'START',
	GAME_ACTION_DONE: 'DONE',
	GAME_ACTION_WAIT: 'WAIT',
	GAME_ACTION_NOW: 'NOW',
	GAME_ACTION_RESET: 'RESET',
	GAME_RACE_MAX_SECONDS: 15
};